# secrets.yaml
apiVersion: krmfnsops.kaweezle.com/v1alpha1
kind: Secrets
metadata:
    name: all-my-secrets
    annotations:
        # this annotation will keep the resource out of the output
        krmfnsops.kaweezle.com/keep-local-config: "true"
        # this annotation will perform decryption for us
        config.kubernetes.io/function: |
            exec:
              path: ../../krmfnsops
data:
    github:
        password: gh_<github_token>
        application_secret: <secret>
    ovh:
        consumer_key: <secret>
        application_secret: <secret>
